### ISSUE TITLE
pre_trained_model

### ISSUE THREAD

**Issue by Tianming40** [eurecom-asp/pc-darts-anti-spoofing#2]
Dear author

Hello, I now want to use the pre-trained model to detect some wild data sets, but I directly used the 4-16.pth model under pre_trained_model, and the results were very poor. I want to know the three in the pre_trained_model folder Are all models pre-trained, or do I need to train them myself?
best regards,
Tianming

**Comment by GeWanying** [comment]
Hi,

All the three .pth files are models pre-trained on the ASVspoof 2019 LA database. If your wild data sets have training partition, I suggest you to train again yourself on that partition, or maybe add with the ASVspoof data; if you are thinking to retrain the model again but still with the original ASVspoof 2019 LA, I don't think it's necessary since you will probably observe the same poor result after retraining.

I'm not surprised that you are not getting good result, one reason is that the test data is in-the-wild, another reason is that the PC-DARTS model itself is not competitive among other systems. And we find in our latter paper that this model uses silence (but supposed to be speech) information for spoofing detection, which will also make it less robust facing wild data, or even original but trimmed ASVspoof data.

If you simply want good result for detecting wild data, I suggest to try some recent systems like [SSL_Anti-spoofing](https://github.com/TakHemlata/SSL_Anti-spoofing) and [aasist](https://github.com/clovaai/aasist). 

Hope I answered your question well.
